services:
  yolo-intel:
    build: .                    # Tells Compose to build the local Dockerfile
    container_name: yolo_arc_webcam
    stdin_open: true
    tty: true
    ipc: host
    privileged: true
    ports:
      - "5000:5000"             
    devices:
      - /dev/dri:/dev/dri       
      - /dev/video0:/dev/video0 
    volumes:
      - .:/app                  
    working_dir: /app
    #command: python web_app.py  # Automatically starts the web server on boot!